version: '2'
services:

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./Project:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
    links:
      - "db:db"

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - "8080:80"


  db:
    image: mysql:8
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=kraken"
      - "MYSQL_USER=kraken"
      - "MYSQL_PASSWORD=kraken"
      - "MYSQL_ROOT_PASSWORD=kraken"
    ports:
      - "33061:3306"

  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  dbdata: