version: '2'
services:

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./KrakenSecurity:/var/www
      - ./TestingArea:/var/testing
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
    links:
      - "db:db"

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - "8080:80"


  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=kraken"
      - "MYSQL_USER=kraken"
      - "MYSQL_PASSWORD=kraken"
      - "MYSQL_ROOT_PASSWORD=kraken"
    ports:
      - "33061:3306"

  composer:
    restart: 'no'
    image: composer:latest
    command: install
    volumes_from:
        - app
    working_dir: /var/www/KrakenSecurity

volumes:
  dbdata:



