version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=kraken"
      - "MYSQL_USER=kraken"
      - "MYSQL_PASSWORD=kraken"
      - "MYSQL_ROOT_PASSWORD=kraken"
    ports:
      - "3306:3306"
  app:
    build:
      context: ../
      dockerfile: DockerConfig/dockerFiles/app/app.dockerfile
    working_dir: /var/www
    ports:
      - "8080:80"
    links:
      - "db:db"
      # - "postfix"
  # postfix:
  #   image: catatnight/postfix
  #   environment:
  #     - maildomain=it-squad.fr
  #     - smtp_user=user:pass
  #   expose:
  #     - 25:25
  redis:
    image: redis
    ports: 
      - "6379"
volumes:
  dbdata:
